import { Team, Player, Position } from './types';

// Função auxiliar para gerar jogadores balanceados
function createPlayer(id: string, name: string, position: Position, overall: number, age: number, isStarter: boolean): Player {
  const tec = Math.min(9, Math.max(1, overall + Math.floor(Math.random() * 3) - 1));
  const fis = Math.min(9, Math.max(1, overall + Math.floor(Math.random() * 3) - 1));
  const dec = Math.min(9, Math.max(1, overall + Math.floor(Math.random() * 3) - 1));
  
  // Tabela Elifoot base
  const baseValues: Record<number, number> = {
    1: 300_000,
    2: 600_000,
    3: 1_000_000,
    4: 2_500_000,
    5: 5_000_000,
    6: 10_000_000,
    7: 20_000_000,
    8: 40_000_000,
    9: 80_000_000,
  };
  
  let val = baseValues[overall] || 1_000_000;
  if (age <= 21) val *= 1.15;
  else if (age >= 29 && age <= 32) val *= 0.90;
  else if (age >= 33) val *= 0.75;

  return {
    id,
    name,
    position,
    overall,
    age,
    tec,
    fis,
    dec,
    evolutionPoints: 0,
    marketValue: Math.round(val),
    isStarter,
  };
}

export const LEAGUE_TEAMS: Team[] = [
  {
    id: 'lusitano',
    name: 'Lusitano Ginásio',
    shortName: 'LUS',
    primaryColor: '#16a34a', // Verde
    secondaryColor: '#ffffff',
    isBot: false,
    tactics: {
      formation: '4-3-3',
      mentality: 'balanced',
      pressing: 'high',
      buildup: 'tiki_taka',
    },
    players: [
      createPlayer('lus_1', 'Rui Patrício', 'GR', 7, 28, true),
      createPlayer('lus_2', 'João Cancelo', 'DF', 7, 26, true),
      createPlayer('lus_3', 'Rúben Dias', 'DF', 8, 25, true),
      createPlayer('lus_4', 'Gonçalo Inácio', 'DF', 7, 22, true),
      createPlayer('lus_5', 'Nuno Mendes', 'DF', 7, 21, true),
      createPlayer('lus_6', 'João Palhinha', 'MD', 7, 27, true),
      createPlayer('lus_7', 'Vitinha', 'MD', 8, 23, true),
      createPlayer('lus_8', 'Bernardo Silva', 'MD', 8, 29, true),
      createPlayer('lus_9', 'Pedro Neto', 'AV', 7, 23, true),
      createPlayer('lus_10', 'Gonçalo Ramos', 'AV', 7, 22, true),
      createPlayer('lus_11', 'Rafael Leão', 'AV', 8, 24, true),
      // Suplentes
      createPlayer('lus_12', 'Diogo Costa', 'GR', 6, 21, false),
      createPlayer('lus_13', 'António Silva', 'DF', 6, 20, false),
      createPlayer('lus_14', 'Matheus Nunes', 'MD', 6, 24, false),
      createPlayer('lus_15', 'Chiquinho', 'MD', 5, 26, false),
      createPlayer('lus_16', 'Fábio Silva', 'AV', 6, 21, false),
    ],
  },
  {
    id: 'estrela_ribatejo',
    name: 'Estrela do Ribatejo',
    shortName: 'EST',
    primaryColor: '#dc2626', // Vermelho
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-4-2',
      mentality: 'attacking',
      pressing: 'balanced',
      buildup: 'direct',
    },
    players: [
      createPlayer('est_1', 'Vítor Baía', 'GR', 8, 30, true),
      createPlayer('est_2', 'Secretário', 'DF', 6, 29, true),
      createPlayer('est_3', 'Jorge Costa', 'DF', 7, 28, true),
      createPlayer('est_4', 'Fernando Couto', 'DF', 8, 29, true),
      createPlayer('est_5', 'Dimas Teixeira', 'DF', 6, 27, true),
      createPlayer('est_6', 'Paulo Bento', 'MD', 7, 30, true),
      createPlayer('est_7', 'Costinha', 'MD', 6, 26, true),
      createPlayer('est_8', 'Rui Costa', 'MD', 8, 27, true),
      createPlayer('est_9', 'Luís Figo', 'MD', 9, 27, true),
      createPlayer('est_10', 'João Pinto', 'AV', 7, 28, true),
      createPlayer('est_11', 'Pauleta', 'AV', 8, 26, true),
      // Suplentes
      createPlayer('est_12', 'Quim Silva', 'GR', 6, 25, false),
      createPlayer('est_13', 'Beto Severo', 'DF', 6, 23, false),
      createPlayer('est_14', 'Vidigal', 'MD', 6, 26, false),
      createPlayer('est_15', 'Capucho', 'MD', 6, 27, false),
      createPlayer('est_16', 'Nuno Gomes', 'AV', 7, 23, false),
    ],
  },
  {
    id: 'atletico_porto',
    name: 'Atlético do Douro',
    shortName: 'ATD',
    primaryColor: '#2563eb', // Azul
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-4-2',
      mentality: 'balanced',
      pressing: 'high',
      buildup: 'tiki_taka',
    },
    players: [
      createPlayer('atd_1', 'Helton Arruda', 'GR', 7, 29, true),
      createPlayer('atd_2', 'Fucile', 'DF', 6, 25, true),
      createPlayer('atd_3', 'Rolando', 'DF', 6, 24, true),
      createPlayer('atd_4', 'Bruno Alves', 'DF', 7, 28, true),
      createPlayer('atd_5', 'Álvaro Pereira', 'DF', 6, 25, true),
      createPlayer('atd_6', 'Fernando Reges', 'MD', 7, 23, true),
      createPlayer('atd_7', 'Fredy Guarín', 'MD', 6, 24, true),
      createPlayer('atd_8', 'João Moutinho', 'MD', 8, 24, true),
      createPlayer('atd_9', 'James Rodríguez', 'MD', 7, 20, true),
      createPlayer('atd_10', 'Hulk Paraíba', 'AV', 8, 25, true),
      createPlayer('atd_11', 'Falcao García', 'AV', 8, 25, true),
      // Suplentes
      createPlayer('atd_12', 'Beto Pimparel', 'GR', 6, 28, false),
      createPlayer('atd_13', 'Maicon Roque', 'DF', 6, 22, false),
      createPlayer('atd_14', 'Souza', 'MD', 5, 21, false),
      createPlayer('atd_15', 'Silvestre Varela', 'AV', 6, 26, false),
      createPlayer('atd_16', 'Walter Bigode', 'AV', 5, 21, false),
    ],
  },
  {
    id: 'vitoria_maritima',
    name: 'Vitória Marítima',
    shortName: 'VMA',
    primaryColor: '#0891b2', // Ciano
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '5-3-2',
      mentality: 'defensive',
      pressing: 'low',
      buildup: 'direct',
    },
    players: [
      createPlayer('vma_1', 'Marcos Miranda', 'GR', 6, 31, true),
      createPlayer('vma_2', 'Briguel', 'DF', 6, 30, true),
      createPlayer('vma_3', 'Mitchell van der Gaag', 'DF', 6, 29, true),
      createPlayer('vma_4', 'Evaldo Silva', 'DF', 6, 27, true),
      createPlayer('vma_5', 'Fernando Cardozo', 'DF', 5, 24, true),
      createPlayer('vma_6', 'Kikas Ramos', 'DF', 5, 23, true),
      createPlayer('vma_7', 'Sérgio Organista', 'MD', 5, 25, true),
      createPlayer('vma_8', 'Babá Diawara', 'MD', 6, 23, true),
      createPlayer('vma_9', 'Marquinho Carioca', 'MD', 5, 26, true),
      createPlayer('vma_10', 'Djalma Campos', 'AV', 6, 23, true),
      createPlayer('vma_11', 'Kléber Laube', 'AV', 6, 20, true),
      // Suplentes
      createPlayer('vma_12', 'Peçanha', 'GR', 5, 28, false),
      createPlayer('vma_13', 'Robson Bambu', 'DF', 5, 21, false),
      createPlayer('vma_14', 'Roberto Sousa', 'MD', 5, 26, false),
      createPlayer('vma_15', 'Tchô', 'MD', 5, 23, false),
      createPlayer('vma_16', 'Fidélis', 'AV', 4, 19, false),
    ],
  },
  {
    id: 'real_mirandela',
    name: 'Real Mirandela',
    shortName: 'RMI',
    primaryColor: '#d97706', // Âmbar
    secondaryColor: '#1e293b',
    isBot: true,
    tactics: {
      formation: '4-4-2',
      mentality: 'balanced',
      pressing: 'balanced',
      buildup: 'balanced',
    },
    players: [
      createPlayer('rmi_1', 'Tiago Sá', 'GR', 6, 26, true),
      createPlayer('rmi_2', 'Vasco Fernandes', 'DF', 5, 28, true),
      createPlayer('rmi_3', 'Pedro Mendes', 'DF', 6, 27, true),
      createPlayer('rmi_4', 'Frederico Venâncio', 'DF', 5, 25, true),
      createPlayer('rmi_5', 'Tiago Pinto', 'DF', 5, 28, true),
      createPlayer('rmi_6', 'Tomás Podstawski', 'MD', 5, 24, true),
      createPlayer('rmi_7', 'Filipe Augusto', 'MD', 6, 26, true),
      createPlayer('rmi_8', 'André Horta', 'MD', 6, 23, true),
      createPlayer('rmi_9', 'Fábio Martins', 'MD', 6, 25, true),
      createPlayer('rmi_10', 'Rui Fonte', 'AV', 6, 27, true),
      createPlayer('rmi_11', 'Paulinho Fernandes', 'AV', 7, 26, true),
      // Suplentes
      createPlayer('rmi_12', 'Marafona', 'GR', 5, 30, false),
      createPlayer('rmi_13', 'Nuno Sequeira', 'DF', 5, 27, false),
      createPlayer('rmi_14', 'Fransérgio', 'MD', 6, 28, false),
      createPlayer('rmi_15', 'Murilo de Souza', 'MD', 5, 23, false),
      createPlayer('rmi_16', 'Wilson Eduardo', 'AV', 5, 27, false),
    ],
  },
  {
    id: 'uniao_coimbra',
    name: 'União Académica de Coimbra',
    shortName: 'UAC',
    primaryColor: '#000000', // Preto
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-3-3',
      mentality: 'attacking',
      pressing: 'high',
      buildup: 'tiki_taka',
    },
    players: [
      createPlayer('uac_1', 'Pedro Roma', 'GR', 6, 32, true),
      createPlayer('uac_2', 'Pedro Silva', 'DF', 5, 27, true),
      createPlayer('uac_3', 'Tonel', 'DF', 6, 29, true),
      createPlayer('uac_4', 'Zé Castro', 'DF', 6, 26, true),
      createPlayer('uac_5', 'Hélder Cabral', 'DF', 5, 25, true),
      createPlayer('uac_6', 'Nuno Piloto', 'MD', 5, 27, true),
      createPlayer('uac_7', 'Diogo Melo', 'MD', 5, 26, true),
      createPlayer('uac_8', 'Adrien Silva', 'MD', 7, 22, true),
      createPlayer('uac_9', 'Marinho', 'AV', 5, 26, true),
      createPlayer('uac_10', 'Éderzito Lopes', 'AV', 6, 23, true),
      createPlayer('uac_11', 'Licá', 'AV', 6, 24, true),
      // Suplentes
      createPlayer('uac_12', 'Ricardo Janota', 'GR', 4, 23, false),
      createPlayer('uac_13', 'João Real', 'DF', 5, 28, false),
      createPlayer('uac_14', 'Cleyton', 'MD', 5, 25, false),
      createPlayer('uac_15', 'Saleh', 'MD', 4, 21, false),
      createPlayer('uac_16', 'Edinho', 'AV', 5, 28, false),
    ],
  },
  {
    id: 'gd_alentejano',
    name: 'GD Alentejano',
    shortName: 'GDA',
    primaryColor: '#854d0e', // Castanho dourado
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-4-2',
      mentality: 'balanced',
      pressing: 'balanced',
      buildup: 'direct',
    },
    players: [
      createPlayer('gda_1', 'Mika Domingues', 'GR', 5, 25, true),
      createPlayer('gda_2', 'Hugo Carreira', 'DF', 5, 29, true),
      createPlayer('gda_3', 'Danielson', 'DF', 6, 30, true),
      createPlayer('gda_4', 'Vítor Vinha', 'DF', 5, 26, true),
      createPlayer('gda_5', 'Mamadu Candé', 'DF', 5, 24, true),
      createPlayer('gda_6', 'Pelé Monteiro', 'MD', 5, 23, true),
      createPlayer('gda_7', 'Tarantini', 'MD', 6, 31, true),
      createPlayer('gda_8', 'Rafa Silva', 'MD', 7, 21, true),
      createPlayer('gda_9', 'Ukra Monteiro', 'MD', 6, 26, true),
      createPlayer('gda_10', 'Ahmed Hassan', 'AV', 6, 22, true),
      createPlayer('gda_11', 'João Tomás', 'AV', 6, 33, true),
      // Suplentes
      createPlayer('gda_12', 'Carlos Fernandes', 'GR', 4, 32, false),
      createPlayer('gda_13', 'Nélson Monte', 'DF', 4, 20, false),
      createPlayer('gda_14', 'Witi', 'MD', 5, 22, false),
      createPlayer('gda_15', 'Lionn', 'DF', 5, 26, false),
      createPlayer('gda_16', 'Esmaël Gonçalves', 'AV', 5, 24, false),
    ],
  },
  {
    id: 'sc_farense_oriental',
    name: 'SC Farense Oriental',
    shortName: 'FAR',
    primaryColor: '#059669', // Esmeralda
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-3-3',
      mentality: 'balanced',
      pressing: 'balanced',
      buildup: 'balanced',
    },
    players: [
      createPlayer('far_1', 'Hugo Ventura', 'GR', 5, 27, true),
      createPlayer('far_2', 'Carlitos', 'DF', 5, 28, true),
      createPlayer('far_3', 'Cássio', 'DF', 5, 29, true),
      createPlayer('far_4', 'Eduardo Mancha', 'DF', 5, 25, true),
      createPlayer('far_5', 'Abner Felipe', 'DF', 5, 23, true),
      createPlayer('far_6', 'Fabrício Isidoro', 'MD', 5, 27, true),
      createPlayer('far_7', 'Ryan Gauld', 'MD', 7, 24, true),
      createPlayer('far_8', 'Jonatan Lucca', 'MD', 6, 25, true),
      createPlayer('far_9', 'Madi Queta', 'AV', 5, 22, true),
      createPlayer('far_10', 'Pedro Henrique', 'AV', 6, 26, true),
      createPlayer('far_11', 'Mansilla', 'AV', 5, 24, true),
      // Suplentes
      createPlayer('far_12', 'Rafael Defendi', 'GR', 5, 33, false),
      createPlayer('far_13', 'Robson', 'DF', 4, 27, false),
      createPlayer('far_14', 'Claudio Falcão', 'MD', 5, 26, false),
      createPlayer('far_15', 'Alvarinho', 'MD', 4, 25, false),
      createPlayer('far_16', 'Mayambela', 'AV', 5, 23, false),
    ],
  },
  {
    id: 'sporting_ilhas',
    name: 'Sporting das Ilhas',
    shortName: 'SIL',
    primaryColor: '#4f46e5', // Índigo
    secondaryColor: '#ffffff',
    isBot: true,
    tactics: {
      formation: '4-2-3-1',
      mentality: 'attacking',
      pressing: 'high',
      buildup: 'tiki_taka',
    },
    players: [
      createPlayer('sil_1', 'Marco Pereira', 'GR', 6, 30, true),
      createPlayer('sil_2', 'Rafael Ramos', 'DF', 5, 25, true),
      createPlayer('sil_3', 'Fábio Cardoso', 'DF', 6, 26, true),
      createPlayer('sil_4', 'Mikel Villanueva', 'DF', 5, 27, true),
      createPlayer('sil_5', 'Mansur', 'DF', 5, 26, true),
      createPlayer('sil_6', 'Hidemasa Morita', 'MD', 7, 26, true),
      createPlayer('sil_7', 'Anderson Carvalho', 'MD', 6, 28, true),
      createPlayer('sil_8', 'Lincoln Henrique', 'MD', 7, 22, true),
      createPlayer('sil_9', 'Cryzan', 'AV', 6, 24, true),
      createPlayer('sil_10', 'Carlos Júnior', 'AV', 6, 25, true),
      createPlayer('sil_11', 'Rui Costa II', 'AV', 5, 24, true),
      // Suplentes
      createPlayer('sil_12', 'André Ferreira', 'GR', 5, 24, false),
      createPlayer('sil_13', 'João Afonso', 'DF', 5, 30, false),
      createPlayer('sil_14', 'Nené', 'MD', 5, 25, false),
      createPlayer('sil_15', 'Costinha II', 'MD', 4, 21, false),
      createPlayer('sil_16', 'Allano', 'AV', 5, 25, false),
    ],
  },
  {
    id: 'dragoes_gaia',
    name: 'Dragões de Gaia',
    shortName: 'DGA',
    primaryColor: '#1d4ed8', // Azul royal
    secondaryColor: '#fbbf24',
    isBot: true,
    tactics: {
      formation: '4-3-3',
      mentality: 'balanced',
      pressing: 'balanced',
      buildup: 'balanced',
    },
    players: [
      createPlayer('dga_1', 'Cláudio Ramos', 'GR', 6, 29, true),
      createPlayer('dga_2', 'João Mário II', 'DF', 6, 21, true),
      createPlayer('dga_3', 'Diogo Leite', 'DF', 6, 22, true),
      createPlayer('dga_4', 'David Carmo', 'DF', 6, 23, true),
      createPlayer('dga_5', 'Zaidu Sanusi', 'DF', 5, 24, true),
      createPlayer('dga_6', 'Stephen Eustáquio', 'MD', 6, 24, true),
      createPlayer('dga_7', 'Marko Grujic', 'MD', 6, 25, true),
      createPlayer('dga_8', 'Otávio Monteiro', 'MD', 7, 26, true),
      createPlayer('dga_9', 'Pepê Aquino', 'AV', 7, 24, true),
      createPlayer('dga_10', 'Evanilson', 'AV', 7, 22, true),
      createPlayer('dga_11', 'Toni Martínez', 'AV', 6, 24, true),
      // Suplentes
      createPlayer('dga_12', 'Samuel Portugal', 'GR', 5, 27, false),
      createPlayer('dga_13', 'Wilson Manafá', 'DF', 5, 27, false),
      createPlayer('dga_14', 'Bernardo Folha', 'MD', 5, 20, false),
      createPlayer('dga_15', 'Danny Namaso', 'AV', 5, 21, false),
      createPlayer('dga_16', 'Gonçalo Borges', 'AV', 5, 20, false),
    ],
  },
  {
    id: 'aguias_sintra',
    name: 'Águias de Sintra',
    shortName: 'ASI',
    primaryColor: '#b91c1c', // Vermelho escuro
    secondaryColor: '#facc15',
    isBot: true,
    tactics: {
      formation: '4-4-2',
      mentality: 'balanced',
      pressing: 'high',
      buildup: 'tiki_taka',
    },
    players: [
      createPlayer('asi_1', 'Samuel Soares', 'GR', 6, 20, true),
      createPlayer('asi_2', 'Alexander Bah', 'DF', 6, 24, true),
      createPlayer('asi_3', 'Morato', 'DF', 6, 21, true),
      createPlayer('asi_4', 'Lucas Veríssimo', 'DF', 6, 26, true),
      createPlayer('asi_5', 'Mihailo Ristic', 'DF', 5, 26, true),
      createPlayer('asi_6', 'Florentino Luís', 'MD', 7, 23, true),
      createPlayer('asi_7', 'Chiquinho Machado', 'MD', 6, 26, true),
      createPlayer('asi_8', 'João Mário', 'MD', 7, 29, true),
      createPlayer('asi_9', 'David Neres', 'MD', 7, 25, true),
      createPlayer('asi_10', 'Petar Musa', 'AV', 6, 24, true),
      createPlayer('asi_11', 'Casper Tengstedt', 'AV', 6, 22, true),
      // Suplentes
      createPlayer('asi_12', 'André Gomes', 'GR', 5, 18, false),
      createPlayer('asi_13', 'João Victor', 'DF', 5, 24, false),
      createPlayer('asi_14', 'Paulo Bernardo', 'MD', 5, 20, false),
      createPlayer('asi_15', 'Tiago Gouveia', 'AV', 5, 21, false),
      createPlayer('asi_16', 'Henrique Araújo', 'AV', 5, 20, false),
    ],
  },
  {
    id: 'boavista_academico',
    name: 'Boavista Académico',
    shortName: 'BOA',
    primaryColor: '#0f172a', // Preto xadrez
    secondaryColor: '#f8fafc',
    isBot: true,
    tactics: {
      formation: '5-3-2',
      mentality: 'ultra_defensive',
      pressing: 'balanced',
      buildup: 'direct',
    },
    players: [
      createPlayer('boa_1', 'Rafael Bracali', 'GR', 6, 39, true),
      createPlayer('boa_2', 'Reggie Cannon', 'DF', 6, 23, true),
      createPlayer('boa_3', 'Vincent Sasso', 'DF', 5, 30, true),
      createPlayer('boa_4', 'Rodrigo Abascal', 'DF', 6, 27, true),
      createPlayer('boa_5', 'Sopuruchukwu Onyemaechi', 'DF', 5, 22, true),
      createPlayer('boa_6', 'Pedro Malheiro', 'DF', 6, 20, true),
      createPlayer('boa_7', 'Sebastián Pérez', 'MD', 6, 28, true),
      createPlayer('boa_8', 'Gaius Makouta', 'MD', 6, 24, true),
      createPlayer('boa_9', 'Ilija Vukotic', 'MD', 5, 22, true),
      createPlayer('boa_10', 'Salvador Agra', 'AV', 5, 30, true),
      createPlayer('boa_11', 'Yusupha Njie', 'AV', 6, 27, true),
      // Suplentes
      createPlayer('boa_12', 'César Bernardo', 'GR', 5, 29, false),
      createPlayer('boa_13', 'Robson Reis', 'DF', 4, 21, false),
      createPlayer('boa_14', 'Ibrahima Camará', 'MD', 5, 22, false),
      createPlayer('boa_15', 'Kenji Gorré', 'AV', 5, 26, false),
      createPlayer('boa_16', 'Róbert Bozeník', 'AV', 6, 22, false),
    ],
  },
];
